[env]
platform = espressif32@6.7.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv

upload_protocol = esptool
upload_speed = 921600 

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    bblanchon/ArduinoJson @ ^7.0.0

build_type = release
build_unflags = -Os
build_flags =
    -O3
    -D CONFIG_DISABLE_HAL_LOCKS=1
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_RST=4
    -D TFT_DC=15
    -D TFT_CS=-1
    -D DISABLE_TOUCH=1
    -D TOUCH_CS=-1
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=40000000

; Прошивка с имитацией температур (для отладки без автомобиля)
[env:esp32-mock]
build_flags =
    ${env.build_flags}
    -D USE_MOCK_DATA

; Прошивка с реальными данными из CAN-шины
[env:esp32]
