[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43

build_flags =
    -D USER_SETUP_LOADED=1      ; Указываем библиотеке использовать наши настройки
    -D ST7789_DRIVER=1          ; Драйвер нашего дисплея
    -D TFT_WIDTH=240            ; Разрешение экрана
    -D TFT_HEIGHT=240           
    -D TFT_MOSI=23              ; Пин SDA -> D23
    -D TFT_SCLK=18              ; Пин SCL -> D18
    -D TFT_RST=4                ; Пин RES -> D4
    -D TFT_DC=15                ; Пин DC -> D15
    -D LOAD_GLCD=1              ; Загружаем стандартные шрифты
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=40000000   ; Частота шины SPI 40 МГц для высокой скорости
